{% set name = "s1reader" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/isce-framework/s1-reader/archive/v{{ version }}.tar.gz
  sha256: 3086dc5f9687dbbc4b815ebba09aa32dbff8984d385bb6e16ecd95edabe4a327

build:
  entry_points:
    - s1_info = s1reader.s1_info:main
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42.0
    - pip >=21.3
  run:
    - python >=3.8
    - numpy >=1.20
    - gdal >=3.0
    - isce3 >=0.13
    - packaging >=21.0
    - requests >=2.0
    - shapely >=1.8
    - lxml >=4.8
    - importlib-resources # Next release will remove this dependency

test:
  imports:
    - s1reader
  commands:
    - pip check
    - s1_info --help
  requires:
    - pip

about:
  home: https://github.com/isce-framework/s1-reader
  summary: A Sentinel-1 reader for ISCE3
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/isce-framework/s1-reader

extra:
  recipe-maintainers:
    - scottstanie
    - seongsujeong
    - rtburns-jpl
